version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21  # Specify the Node.js version
    commands:
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - cd server
      - echo "Installing dependencies..."
      - bun install  # Install dependencies defined in package.json

  pre_build:
    commands:
      - echo "Pre build compilation..."
  build:
    commands:
      - echo "Compile tsc-alias..."
      - npx tsc && npx tsc-alias  # Run tsc-alias after tsc

  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '**/*'  # Include all files from the base directory
  base-directory: server/dist  # Adjust the base directory to where your build output is
  discard-paths: no
  name: source_code/  # Store the artifacts in the 'source_code' folder in S3