version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21  # Specify the Node.js version
    commands:
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - cd server
      - echo "Installing dependencies..."
      - bun install  # Install dependencies defined in package.json

  pre_build:
    commands:
      - echo "Running TypeScript compilation..."
      - npx tsc  # Run TypeScript compiler (tsc)

  build:
    commands:
      - echo "Applying tsc-alias..."
      - npx tsc-alias  # Run tsc-alias after tsc

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'  # Include all files from the base directory
  discard-paths: no
  # The following line specifies the S3 bucket and folder (key) where the artifacts will be stored
  name: source_code/  # Store the artifacts in the 'source_code' folder in S3