services:
  app:
    container_name: personal-blog-server
    build:
      context: .
      dockerfile: Dockerfile
    image: personal-blog-server
    ports:
      - "5500:5500"
    volumes:
      - .:/app
    command: ["node", "-r", "tsconfig-paths/register", "dist/server.js"]
